version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/
    
permissions:
  - object: /var/www/html
    pattern: ".sh"
    owner: ec2-user
    group: ec2-user
    mode: 700
    type:
      - file
    
   
hooks:
  AfterInstall:
    - location: set-permissions.sh
    
